### ISSUE TITLE
DNCON4_prediction_other shape error.

### ISSUE THREAD

**Issue by 595693085** [multicom-toolbox/deepdist#1]
Hi,
I'm running the script for residue-residue distance prediction with an error.
...
start predict T1019s1 58
*********deepdist/lib/Model_predict_v2.py", line 394, in <module>
    CMAP = DNCON4_prediction_other.reshape(Maximum_length, Maximum_length)
ValueError: cannot reshape array of size 141288 into shape (58,58)
It seems that 141288 shold be shaped as (42,58,58), but not (58,58)
the script is running with msa and fasta as input.
Could you tell me how to fix the error, thank you.
By the way, the shell command i used is 
python ***/deepdist/lib/Model_predict_v2.py ***/deepdist example/T1019s1.fasta example/T1019s1.aln ***/deepdist/models/pretrain/MULTICOM-DIST/1.dres152_deepcov_cov_ccmpred_pearson_pssm/ ***/deepdist/models/pretrain/MULTICOM-DIST/2.dres152_deepcov_plm_pearson_pssm/ ***/deepdist/models/pretrain/MULTICOM-DIST/3.res152_deepcov_pre_freecontact/ ***/deepdist/models/pretrain/MULTICOM-DIST/4.res152_deepcov_other/  predictors/results/T1019s1 'mul_label_R'
because there will be a lot of "ModuleNotFoundError" errors following your readme, so i setup the environment myself and run the Model_predict_v2.py directly.

**Comment by 595693085** [comment]
i have found the reason. The parameter you provided in readme is 'mul_label_R', but the paramerter in code for judgement is 'mul_lable_R',  but annother error came up
  File "***/deepdist/lib/Model_predict_v2.py", line 372, in <module>
    DNCON4_prediction_mul_class= DNCON4_prediction_other[0][:,:,:,0:8].sum(axis=-1)
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

**Comment by ZhiYeG** [comment]
Hi 
Sorry for the late reply, the DeepDist has been updated to version2 and fix several bugs, you may try to download the new version for your prediction.

**Comment by 595693085** [comment]
Thanks, I'll try again.
