### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IanMcDowell** [multicom-toolbox/deepdist#11]
This package seems attractive for commercial use: pre-trained, well-documented, apparently easy to run (or so it seems from the README), but I don't see a LICENSE. Could one be added? Or rather, may I use this for commercial use? (I'm not a lawyer; I am looking into using this package for some protein engineering work and some machine learning applications.) Thank you.

**Comment by jianlin-cheng** [comment]
The GNU 3.0 license is applied to this software. A license file has been added into the repository. You may use the software for commercial purpose.

**Comment by IanMcDowell** [comment]
Great, many thanks!
