### ISSUE TITLE
About setup_fasta.py

### ISSUE THREAD

**Issue by iron-wang** [multicom-toolbox/deepdist#13]
Hi,When I setup_msa.py or setup_fasta.py, An error occurred，The error message is “Fail to download blast-2.2.26-x64-linux.tar.gz from http://sysbio.rnet.missouri.edu/dncon4_db_tools/tools/blast-2.2.26-x64-linux.tar.gz”.It seems that this link is dead。Do You Know how to solve ?

**Comment by ZhiYeG** [comment]
Hi,
We recently participated in CASP, so the server is not open to the public. Sorry for the inconvenience, you may try it after September.
