### ISSUE TITLE
CASP14_MSA files

### ISSUE THREAD

**Issue by nasserhashemi** [multicom-toolbox/deepdist#4]
Hi, 
Thanks foir sharing your great job; 
Is it possible to share the MSA file associated with CASP14? 
Thanks 
Nasser

**Comment by ZhiYeG** [comment]
Hi,
I already upload the CASP14 MSA file into ./example/alignments/. Notice that all the MSAs are for the CASP14 31 FM and FM/TBM  full-length targets.
