### ISSUE TITLE
Error in setup.msa

### ISSUE THREAD

**Issue by tungnguyen1234** [multicom-toolbox/deepdist#6]
Hi I'm Tung, and I am implementing deepdist. There is the following issue when I run "python msa.py":

**Error: [Errno 5] Input/output error: 'lib' -> '/content/onedrive/deepdist/env/deepdist_virenv/lib64'
/content/onedrive/deepdist/installation/set_env.sh: line 11: /content/onedrive/deepdist/env/deepdist_virenv/bin/activate: No such file or directory
Failed to set virtual environment....**

If possible, could you check on this?

**Comment by ZhiYeG** [comment]
Hi,

Try to install the virtual environment manually by running 'sh ./installation/set_env.sh'. And please make sure you're using python3.6 as your default python environment. Let me know the output information if it does not work.

**Comment by tungnguyen1234** [comment]
Hi,

Thanks for your reply. I used python 3.6.9 and used your command, but it still shows the same error:

"install virtual environment to /content/onedrive/deepdist/env/
Error: [Errno 5] Input/output error: 'lib' -> '/content/onedrive/deepdist/env/deepdist_virenv/lib64'
./installation/set_env.sh: line 11: /content/onedrive/deepdist/env//deepdist_virenv/bin/activate: No such file or directory"

**Comment by ZhiYeG** [comment]
In this way, your system may can not create the virtual environment by running the shell scripts. You can try to copy the command in the shell script line by line to the terminal to run it. Let me know if this works.

**Comment by tungnguyen1234** [comment]
Hi, so I have tried to run each line in set_env.sh. I thought that maybe it could create the link and folder for '/deepdist_virenv/bin/activate', however it still didn't work. Is there a manual way to set up the folder 'bin' then the subfile 'activate' for '/deepdist_virenv/bin/activate'?

**Comment by ZhiYeG** [comment]
What error you got when you run 'python3 -m venv deepdist_virenv'?

**Comment by tungnguyen1234** [comment]
Error: [Errno 5] Input/output error: 'lib' -> '/content/onedrive/deepdist/env/deepdist_virenv/lib64'

I forgot to add that I'm running everything on Google colab.

**Comment by ZhiYeG** [comment]
Hi,
This error is caused by the Google colab not allow to read&write too many files. Check the link https://linuxpip.org/errno-5-input-output-error/.  So you may try just skip the command 'python3 -m venv deepdist_virenv', instead of running the package installation directly which means you need to run the lines start whit 'pip'.

**Comment by tungnguyen1234** [comment]
Hi, So I run all the way to the part of installing Uniref90, and it shows the following error when running from line 265 to line 270 in 'setup.msa':

"/bin/sh: 1: /content/onedrive/deepdist/tools/hmmer-3.1b2-linux-intel-x86_64/easel/miniapps/esl-sfetch: not found"

The thing is I could find both 'esl-sfetch.c' and 'esl-sfetch.man', but not 'esl-sfetch' in that path. Is it asking for a folder 'esl-sfetch'?
